package response

type HarborResponse struct {
	ID                    string   `json:"id"`
	HarborCode            string   `json:"harbor_code"`
	HarborName            string   `json:"harbor_name"`
	UNLocode              *string  `json:"un_locode"`
	Country               string   `json:"country"`
	Province              string   `json:"province"`
	City                  string   `json:"city"`
	Latitude              *float64 `json:"latitude"`
	Longitude             *float64 `json:"longitude"`
	TimeZone              *string  `json:"time_zone"`
	MaxShipLength         *float64 `json:"max_ship_length"`
	MaxShipBeam           *float64 `json:"max_ship_beam"`
	MaxShipDraft          *float64 `json:"max_ship_draft"`
	BerthCount            *int     `json:"berth_count"`
	AnchorageDepth        *float64 `json:"anchorage_depth"`
	ChannelDepth          *float64 `json:"channel_depth"`
	CargoHandlingCapacity *float64 `json:"cargo_handling_capacity"`
	StorageCapacity       *float64 `json:"storage_capacity"`
	ContactPerson         *string  `json:"contact_person"`
	ContactPhone          *string  `json:"contact_phone"`
	ContactEmail          *string  `json:"contact_email"`
	Website               *string  `json:"website"`
	OperatingHours        *string  `json:"operating_hours"`
	HasPilotage           bool     `json:"has_pilotage"`
	HasTugService         bool     `json:"has_tug_service"`
	HasQuarantine         bool     `json:"has_quarantine"`
	HasCustoms            bool     `json:"has_customs"`
	HasImmigration        bool     `json:"has_immigration"`
	HasSecurity           bool     `json:"has_security"`
	HasMedical            bool     `json:"has_medical"`
	HasRepair             bool     `json:"has_repair"`
	HasSupplies           bool     `json:"has_supplies"`
	HasFuel               bool     `json:"has_fuel"`
	HasWater              bool     `json:"has_water"`
	HasWaste              bool     `json:"has_waste"`
	HasCargo              bool     `json:"has_cargo"`
	HasPassenger          bool     `json:"has_passenger"`
	HasRoro               bool     `json:"has_roro"`
	HasContainer          bool     `json:"has_container"`
	HasBulk               bool     `json:"has_bulk"`
	HasLiquid             bool     `json:"has_liquid"`
	HasBreakbulk          bool     `json:"has_breakbulk"`
	IsActive              bool     `json:"is_active"`
	Notes                 *string  `json:"notes"`
	CreatedAt             int64    `json:"created_at"`
	UpdatedAt             int64    `json:"updated_at"`
}